// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_status1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_status2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_status3;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label4;
void ui_event_ranges(lv_event_t * e);
extern lv_obj_t * ui_ranges;
void ui_event_washing(lv_event_t * e);
extern lv_obj_t * ui_washing;
void ui_event_oven(lv_event_t * e);
extern lv_obj_t * ui_oven;
void ui_event_bed(lv_event_t * e);
extern lv_obj_t * ui_bed;
void ui_event_tv(lv_event_t * e);
extern lv_obj_t * ui_tv;
void ui_event_sink(lv_event_t * e);
extern lv_obj_t * ui_sink;
void ui_event_couch(lv_event_t * e);
extern lv_obj_t * ui_couch;
void ui_event_pc(lv_event_t * e);
extern lv_obj_t * ui_pc;
void ui_event_map(lv_event_t * e);
extern lv_obj_t * ui_map;
void ui_event_h1(lv_event_t * e);
extern lv_obj_t * ui_h1;
void ui_event_h2(lv_event_t * e);
extern lv_obj_t * ui_h2;
void ui_event_h3(lv_event_t * e);
extern lv_obj_t * ui_h3;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label5;
void ui_event_ranges1(lv_event_t * e);
extern lv_obj_t * ui_ranges1;
void ui_event_washing1(lv_event_t * e);
extern lv_obj_t * ui_washing1;
void ui_event_oven1(lv_event_t * e);
extern lv_obj_t * ui_oven1;
void ui_event_bed1(lv_event_t * e);
extern lv_obj_t * ui_bed1;
void ui_event_tv1(lv_event_t * e);
extern lv_obj_t * ui_tv1;
void ui_event_sink1(lv_event_t * e);
extern lv_obj_t * ui_sink1;
void ui_event_couch1(lv_event_t * e);
extern lv_obj_t * ui_couch1;
void ui_event_pc1(lv_event_t * e);
extern lv_obj_t * ui_pc1;
void ui_event_map1(lv_event_t * e);
extern lv_obj_t * ui_map1;
void ui_event_h4(lv_event_t * e);
extern lv_obj_t * ui_h4;
void ui_event_h5(lv_event_t * e);
extern lv_obj_t * ui_h5;
void ui_event_h6(lv_event_t * e);
extern lv_obj_t * ui_h6;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label6;
void ui_event_ranges2(lv_event_t * e);
extern lv_obj_t * ui_ranges2;
void ui_event_washing2(lv_event_t * e);
extern lv_obj_t * ui_washing2;
void ui_event_oven2(lv_event_t * e);
extern lv_obj_t * ui_oven2;
void ui_event_bed2(lv_event_t * e);
extern lv_obj_t * ui_bed2;
void ui_event_tv2(lv_event_t * e);
extern lv_obj_t * ui_tv2;
void ui_event_sink2(lv_event_t * e);
extern lv_obj_t * ui_sink2;
void ui_event_couch2(lv_event_t * e);
extern lv_obj_t * ui_couch2;
void ui_event_pc2(lv_event_t * e);
extern lv_obj_t * ui_pc2;
void ui_event_map2(lv_event_t * e);
extern lv_obj_t * ui_map2;
void ui_event_h7(lv_event_t * e);
extern lv_obj_t * ui_h7;
void ui_event_h8(lv_event_t * e);
extern lv_obj_t * ui_h8;
void ui_event_h9(lv_event_t * e);
extern lv_obj_t * ui_h9;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_86533020);    // assets/3d-house1.png
LV_IMG_DECLARE(ui_img_963246739);    // assets/3d-house2.png
LV_IMG_DECLARE(ui_img_2044975918);    // assets/3d-house3.png
LV_IMG_DECLARE(ui_img_ranges_png);    // assets/ranges.png
LV_IMG_DECLARE(ui_img_1799696388);    // assets/washing-machine.png
LV_IMG_DECLARE(ui_img_oven_png);    // assets/oven.png
LV_IMG_DECLARE(ui_img_bed_png);    // assets/bed.png
LV_IMG_DECLARE(ui_img_television_png);    // assets/television.png
LV_IMG_DECLARE(ui_img_sink_png);    // assets/sink.png
LV_IMG_DECLARE(ui_img_couch_png);    // assets/couch.png
LV_IMG_DECLARE(ui_img_1996329786);    // assets/3d-computer.png
LV_IMG_DECLARE(ui_img_worldwide_png);    // assets/worldwide.png



LV_FONT_DECLARE(ui_font_Font0);
LV_FONT_DECLARE(ui_font_Font2);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
