// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x6713D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 240);
    lv_obj_set_height(ui_Container3, 320);
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, 30);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 2);
    lv_obj_set_align(ui_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label6, "Icon Node 3");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ranges2 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ranges2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ranges_png, NULL);
    lv_imgbtn_set_src(ui_ranges2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_ranges_png, NULL);
    lv_obj_set_height(ui_ranges2, 64);
    lv_obj_set_width(ui_ranges2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ranges2, 20);
    lv_obj_set_y(ui_ranges2, -15);
    lv_obj_set_align(ui_ranges2, LV_ALIGN_LEFT_MID);

    ui_washing2 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_washing2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1799696388, NULL);
    lv_imgbtn_set_src(ui_washing2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1799696388, NULL);
    lv_obj_set_height(ui_washing2, 64);
    lv_obj_set_width(ui_washing2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_washing2, -20);
    lv_obj_set_y(ui_washing2, -15);
    lv_obj_set_align(ui_washing2, LV_ALIGN_RIGHT_MID);

    ui_oven2 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_oven2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_oven_png, NULL);
    lv_imgbtn_set_src(ui_oven2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_oven_png, NULL);
    lv_obj_set_height(ui_oven2, 64);
    lv_obj_set_width(ui_oven2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_oven2, 0);
    lv_obj_set_y(ui_oven2, -15);
    lv_obj_set_align(ui_oven2, LV_ALIGN_CENTER);

    ui_bed2 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_bed2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_bed_png, NULL);
    lv_imgbtn_set_src(ui_bed2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_bed_png, NULL);
    lv_obj_set_height(ui_bed2, 64);
    lv_obj_set_width(ui_bed2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_bed2, 20);
    lv_obj_set_y(ui_bed2, 45);

    ui_tv2 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_tv2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_television_png, NULL);
    lv_imgbtn_set_src(ui_tv2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_television_png, NULL);
    lv_obj_set_height(ui_tv2, 64);
    lv_obj_set_width(ui_tv2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_tv2, 20);
    lv_obj_set_y(ui_tv2, 55);
    lv_obj_set_align(ui_tv2, LV_ALIGN_LEFT_MID);

    ui_sink2 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_sink2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sink_png, NULL);
    lv_imgbtn_set_src(ui_sink2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sink_png, NULL);
    lv_obj_set_height(ui_sink2, 64);
    lv_obj_set_width(ui_sink2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_sink2, -20);
    lv_obj_set_y(ui_sink2, 45);
    lv_obj_set_align(ui_sink2, LV_ALIGN_TOP_RIGHT);

    ui_couch2 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_couch2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_couch_png, NULL);
    lv_imgbtn_set_src(ui_couch2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_couch_png, NULL);
    lv_obj_set_height(ui_couch2, 64);
    lv_obj_set_width(ui_couch2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_couch2, 0);
    lv_obj_set_y(ui_couch2, 45);
    lv_obj_set_align(ui_couch2, LV_ALIGN_TOP_MID);

    ui_pc2 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_pc2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1996329786, NULL);
    lv_imgbtn_set_src(ui_pc2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1996329786, NULL);
    lv_obj_set_height(ui_pc2, 64);
    lv_obj_set_width(ui_pc2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_pc2, 0);
    lv_obj_set_y(ui_pc2, 55);
    lv_obj_set_align(ui_pc2, LV_ALIGN_CENTER);

    ui_map2 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_map2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_worldwide_png, NULL);
    lv_imgbtn_set_src(ui_map2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_worldwide_png, NULL);
    lv_obj_set_height(ui_map2, 64);
    lv_obj_set_width(ui_map2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_map2, -20);
    lv_obj_set_y(ui_map2, 55);
    lv_obj_set_align(ui_map2, LV_ALIGN_RIGHT_MID);

    ui_h7 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_h7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_86533020, NULL);
    lv_imgbtn_set_src(ui_h7, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_86533020, NULL);
    lv_obj_set_height(ui_h7, 64);
    lv_obj_set_width(ui_h7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_h7, 20);
    lv_obj_set_y(ui_h7, 125);
    lv_obj_set_align(ui_h7, LV_ALIGN_LEFT_MID);

    ui_h8 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_h8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_963246739, NULL);
    lv_imgbtn_set_src(ui_h8, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2044975918, NULL);
    lv_obj_set_height(ui_h8, 64);
    lv_obj_set_width(ui_h8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_h8, 0);
    lv_obj_set_y(ui_h8, 125);
    lv_obj_set_align(ui_h8, LV_ALIGN_CENTER);

    ui_h9 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_h9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2044975918, NULL);
    lv_imgbtn_set_src(ui_h9, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2044975918, NULL);
    lv_obj_set_height(ui_h9, 64);
    lv_obj_set_width(ui_h9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_h9, -20);
    lv_obj_set_y(ui_h9, 125);
    lv_obj_set_align(ui_h9, LV_ALIGN_RIGHT_MID);

    lv_obj_add_event_cb(ui_ranges2, ui_event_ranges2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_washing2, ui_event_washing2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_oven2, ui_event_oven2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bed2, ui_event_bed2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tv2, ui_event_tv2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sink2, ui_event_sink2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_couch2, ui_event_couch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pc2, ui_event_pc2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_map2, ui_event_map2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_h7, ui_event_h7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_h8, ui_event_h8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_h9, ui_event_h9, LV_EVENT_ALL, NULL);

}
