// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x6713D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 240);
    lv_obj_set_height(ui_Container2, 320);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 30);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 2);
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "Icon Node 2");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ranges1 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_ranges1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ranges_png, NULL);
    lv_imgbtn_set_src(ui_ranges1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_ranges_png, NULL);
    lv_obj_set_height(ui_ranges1, 64);
    lv_obj_set_width(ui_ranges1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ranges1, 20);
    lv_obj_set_y(ui_ranges1, -15);
    lv_obj_set_align(ui_ranges1, LV_ALIGN_LEFT_MID);

    ui_washing1 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_washing1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1799696388, NULL);
    lv_imgbtn_set_src(ui_washing1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1799696388, NULL);
    lv_obj_set_height(ui_washing1, 64);
    lv_obj_set_width(ui_washing1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_washing1, -20);
    lv_obj_set_y(ui_washing1, -15);
    lv_obj_set_align(ui_washing1, LV_ALIGN_RIGHT_MID);

    ui_oven1 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_oven1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_oven_png, NULL);
    lv_imgbtn_set_src(ui_oven1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_oven_png, NULL);
    lv_obj_set_height(ui_oven1, 64);
    lv_obj_set_width(ui_oven1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_oven1, 0);
    lv_obj_set_y(ui_oven1, -15);
    lv_obj_set_align(ui_oven1, LV_ALIGN_CENTER);

    ui_bed1 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_bed1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_bed_png, NULL);
    lv_imgbtn_set_src(ui_bed1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_bed_png, NULL);
    lv_obj_set_height(ui_bed1, 64);
    lv_obj_set_width(ui_bed1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_bed1, 20);
    lv_obj_set_y(ui_bed1, 45);

    ui_tv1 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_tv1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_television_png, NULL);
    lv_imgbtn_set_src(ui_tv1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_television_png, NULL);
    lv_obj_set_height(ui_tv1, 64);
    lv_obj_set_width(ui_tv1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_tv1, 20);
    lv_obj_set_y(ui_tv1, 55);
    lv_obj_set_align(ui_tv1, LV_ALIGN_LEFT_MID);

    ui_sink1 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_sink1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sink_png, NULL);
    lv_imgbtn_set_src(ui_sink1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sink_png, NULL);
    lv_obj_set_height(ui_sink1, 64);
    lv_obj_set_width(ui_sink1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_sink1, -20);
    lv_obj_set_y(ui_sink1, 45);
    lv_obj_set_align(ui_sink1, LV_ALIGN_TOP_RIGHT);

    ui_couch1 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_couch1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_couch_png, NULL);
    lv_imgbtn_set_src(ui_couch1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_couch_png, NULL);
    lv_obj_set_height(ui_couch1, 64);
    lv_obj_set_width(ui_couch1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_couch1, 0);
    lv_obj_set_y(ui_couch1, 45);
    lv_obj_set_align(ui_couch1, LV_ALIGN_TOP_MID);

    ui_pc1 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_pc1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1996329786, NULL);
    lv_imgbtn_set_src(ui_pc1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1996329786, NULL);
    lv_obj_set_height(ui_pc1, 64);
    lv_obj_set_width(ui_pc1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_pc1, 0);
    lv_obj_set_y(ui_pc1, 55);
    lv_obj_set_align(ui_pc1, LV_ALIGN_CENTER);

    ui_map1 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_map1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_worldwide_png, NULL);
    lv_imgbtn_set_src(ui_map1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_worldwide_png, NULL);
    lv_obj_set_height(ui_map1, 64);
    lv_obj_set_width(ui_map1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_map1, -20);
    lv_obj_set_y(ui_map1, 55);
    lv_obj_set_align(ui_map1, LV_ALIGN_RIGHT_MID);

    ui_h4 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_h4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_86533020, NULL);
    lv_imgbtn_set_src(ui_h4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_86533020, NULL);
    lv_obj_set_height(ui_h4, 64);
    lv_obj_set_width(ui_h4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_h4, 20);
    lv_obj_set_y(ui_h4, 125);
    lv_obj_set_align(ui_h4, LV_ALIGN_LEFT_MID);

    ui_h5 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_h5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_963246739, NULL);
    lv_imgbtn_set_src(ui_h5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2044975918, NULL);
    lv_obj_set_height(ui_h5, 64);
    lv_obj_set_width(ui_h5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_h5, 0);
    lv_obj_set_y(ui_h5, 125);
    lv_obj_set_align(ui_h5, LV_ALIGN_CENTER);

    ui_h6 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_h6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2044975918, NULL);
    lv_imgbtn_set_src(ui_h6, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2044975918, NULL);
    lv_obj_set_height(ui_h6, 64);
    lv_obj_set_width(ui_h6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_h6, -20);
    lv_obj_set_y(ui_h6, 125);
    lv_obj_set_align(ui_h6, LV_ALIGN_RIGHT_MID);

    lv_obj_add_event_cb(ui_ranges1, ui_event_ranges1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_washing1, ui_event_washing1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_oven1, ui_event_oven1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bed1, ui_event_bed1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tv1, ui_event_tv1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sink1, ui_event_sink1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_couch1, ui_event_couch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pc1, ui_event_pc1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_map1, ui_event_map1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_h4, ui_event_h4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_h5, ui_event_h5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_h6, ui_event_h6, LV_EVENT_ALL, NULL);

}
