// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x6713D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 240);
    lv_obj_set_height(ui_Container1, 320);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 30);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 2);
    lv_obj_set_align(ui_Label4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label4, "Icon Node 1");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ranges = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ranges, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ranges_png, NULL);
    lv_imgbtn_set_src(ui_ranges, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_ranges_png, NULL);
    lv_obj_set_height(ui_ranges, 64);
    lv_obj_set_width(ui_ranges, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ranges, 20);
    lv_obj_set_y(ui_ranges, -15);
    lv_obj_set_align(ui_ranges, LV_ALIGN_LEFT_MID);

    ui_washing = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_washing, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1799696388, NULL);
    lv_imgbtn_set_src(ui_washing, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1799696388, NULL);
    lv_obj_set_height(ui_washing, 64);
    lv_obj_set_width(ui_washing, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_washing, -20);
    lv_obj_set_y(ui_washing, -15);
    lv_obj_set_align(ui_washing, LV_ALIGN_RIGHT_MID);

    ui_oven = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_oven, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_oven_png, NULL);
    lv_imgbtn_set_src(ui_oven, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_oven_png, NULL);
    lv_obj_set_height(ui_oven, 64);
    lv_obj_set_width(ui_oven, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_oven, 0);
    lv_obj_set_y(ui_oven, -15);
    lv_obj_set_align(ui_oven, LV_ALIGN_CENTER);

    ui_bed = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_bed, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_bed_png, NULL);
    lv_imgbtn_set_src(ui_bed, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_bed_png, NULL);
    lv_obj_set_height(ui_bed, 64);
    lv_obj_set_width(ui_bed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_bed, 20);
    lv_obj_set_y(ui_bed, 45);

    ui_tv = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_tv, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_television_png, NULL);
    lv_imgbtn_set_src(ui_tv, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_television_png, NULL);
    lv_obj_set_height(ui_tv, 64);
    lv_obj_set_width(ui_tv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_tv, 20);
    lv_obj_set_y(ui_tv, 55);
    lv_obj_set_align(ui_tv, LV_ALIGN_LEFT_MID);

    ui_sink = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_sink, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sink_png, NULL);
    lv_imgbtn_set_src(ui_sink, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_sink_png, NULL);
    lv_obj_set_height(ui_sink, 64);
    lv_obj_set_width(ui_sink, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_sink, -20);
    lv_obj_set_y(ui_sink, 45);
    lv_obj_set_align(ui_sink, LV_ALIGN_TOP_RIGHT);

    ui_couch = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_couch, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_couch_png, NULL);
    lv_imgbtn_set_src(ui_couch, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_couch_png, NULL);
    lv_obj_set_height(ui_couch, 64);
    lv_obj_set_width(ui_couch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_couch, 0);
    lv_obj_set_y(ui_couch, 45);
    lv_obj_set_align(ui_couch, LV_ALIGN_TOP_MID);

    ui_pc = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_pc, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1996329786, NULL);
    lv_imgbtn_set_src(ui_pc, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1996329786, NULL);
    lv_obj_set_height(ui_pc, 64);
    lv_obj_set_width(ui_pc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_pc, 0);
    lv_obj_set_y(ui_pc, 55);
    lv_obj_set_align(ui_pc, LV_ALIGN_CENTER);

    ui_map = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_map, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_worldwide_png, NULL);
    lv_imgbtn_set_src(ui_map, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_worldwide_png, NULL);
    lv_obj_set_height(ui_map, 64);
    lv_obj_set_width(ui_map, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_map, -20);
    lv_obj_set_y(ui_map, 55);
    lv_obj_set_align(ui_map, LV_ALIGN_RIGHT_MID);

    ui_h1 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_h1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_86533020, NULL);
    lv_imgbtn_set_src(ui_h1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_86533020, NULL);
    lv_obj_set_height(ui_h1, 64);
    lv_obj_set_width(ui_h1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_h1, 20);
    lv_obj_set_y(ui_h1, 125);
    lv_obj_set_align(ui_h1, LV_ALIGN_LEFT_MID);

    ui_h2 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_h2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_963246739, NULL);
    lv_imgbtn_set_src(ui_h2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2044975918, NULL);
    lv_obj_set_height(ui_h2, 64);
    lv_obj_set_width(ui_h2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_h2, 0);
    lv_obj_set_y(ui_h2, 125);
    lv_obj_set_align(ui_h2, LV_ALIGN_CENTER);

    ui_h3 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_h3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2044975918, NULL);
    lv_imgbtn_set_src(ui_h3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2044975918, NULL);
    lv_obj_set_height(ui_h3, 64);
    lv_obj_set_width(ui_h3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_h3, -20);
    lv_obj_set_y(ui_h3, 125);
    lv_obj_set_align(ui_h3, LV_ALIGN_RIGHT_MID);

    lv_obj_add_event_cb(ui_ranges, ui_event_ranges, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_washing, ui_event_washing, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_oven, ui_event_oven, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bed, ui_event_bed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tv, ui_event_tv, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sink, ui_event_sink, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_couch, ui_event_couch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pc, ui_event_pc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_map, ui_event_map, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_h1, ui_event_h1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_h2, ui_event_h2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_h3, ui_event_h3, LV_EVENT_ALL, NULL);

}
